theme: "jekyll-theme-slate"
title: "SAP Commercial Project Management"
description: "Using SAP Commercial Project Management to enable the management of prjs  that require light assembly"
show_downloads: false
google_analytics:
github: [metadata]
repository: davebeach/sapcommercialprojects
plugins:
  - "jekyll-github-metadata"
  - "jekyll-watch"
